.PHONY: clean compile_translations coverage diff_cover docs dummy_translations \
        extract_translations fake_translations help \
        quality requirements selfcheck test test-all upgrade validate \
		changelog-entry changelog

.DEFAULT_GOAL := help

# For opening files in a browser. Use like: $(BROWSER)relative/path/to/file.html
BROWSER := python -m webbrowser file://$(CURDIR)/

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

coverage: clean ## generate and view HTML coverage report
	pytest --cov-report html
	$(BROWSER)htmlcov/index.html

docs: ## generate Sphinx HTML documentation, including API docs
	uv sync --group doc
	DJANGO_SETTINGS_MODULE=test_utils.test_settings PYTHONPATH=$(CURDIR) uv run doc8 --ignore-path docs/_build README.rst docs
	rm -f docs/openedx_filters.rst
	rm -f docs/modules.rst
	DJANGO_SETTINGS_MODULE=test_utils.test_settings PYTHONPATH=$(CURDIR) uv run make -C docs clean
	DJANGO_SETTINGS_MODULE=test_utils.test_settings PYTHONPATH=$(CURDIR) uv run make -C docs html
	$(BROWSER)docs/_build/html/index.html

changelog-entry: ## Create a new changelog entry
	scriv create

changelog: ## Collect changelog entries in the CHANGELOG.rst file
	scriv collect

upgrade: ## update the uv.lock file with the latest packages satisfying pyproject.toml
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

quality: ## check coding style with pycodestyle and pylint
	pylint src/openedx_filters test_utils *.py
	mypy
	pycodestyle src/openedx_filters *.py
	ruff check src/openedx_filters *.py
	isort --check-only --diff --recursive test_utils src/openedx_filters *.py test_settings.py
	python -m build --wheel
	twine check dist/*
	make selfcheck


requirements: ## install development environment requirements
	uv sync --group dev

test: clean ## run tests in the current virtualenv
	pytest

diff_cover: test ## find diff lines that need test coverage
	diff-cover coverage.xml

test-all: quality ## run tests on every supported Python/Django combination
	uv run tox

validate: quality test ## run tests and quality checks

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."
